# .github/workflows/build-pdf.yml
name: Build LaTeX PDF

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optional but recommended: cache TeXLive packages for speed
      - name: Cache TeXLive
        uses: actions/cache@v4
        with:
          path: ~/.texlive
          key: texlive-${{ runner.os }}-${{ hashFiles('**/*.tex', '**/*.sty', '**/*.cls', '**/*.bib') }}

      - name: Compile LaTeX
      # Docs: https://github.com/xu-cheng/latex-action
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex         # change if your entry file is different
          latexmk_shell_escape: true  # set false if you don't need shell-escape
          extra_system_packages: >-
            fontconfig
            ghostscript
          # If you use biber:
          # compiler: lualatex
          # args: -synctex=1 -interaction=nonstopmode

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: main.pdf              # or out/main.pdf depending on your setup
